"""
Query Functions Package
======================

Centralized database query functions extracted from Streamlit frontend.
These functions return plain Python data structures (dicts, lists, dataclasses)
with no Streamlit dependencies, making them reusable by both FastAPI and legacy code.
"""

# Import query modules
from .health_queries import (
    get_weight_targets,
    add_weight_target,
    get_weight_viz_data,
    add_photo_metadata,
    add_body_dimensions,
    get_heart_rate_timeseries,
    get_sleep_data,
)
from .music_queries import (
    get_rating_eligible_count,
    get_isrc_dupe_count,
    get_isrc_dupe_match,
    get_playlist_config,
    get_playlist_isrc_stats,
    get_recent_plays,
    get_rating_eligible_playlists,
    get_playlists_not_containing_isrc,
    process_isrc_dupe_acceptance,
    add_isrc_to_local_playlist,
    record_recommendation_decision,
    remove_recommendation,
    add_into_current_ratings,
    update_playlist_config_weights,
    record_rating_history,
    update_ratings_from_view,
    add_soft_rejection_exclusion,
    get_matchup,
    score_matchup,
)
from .admin_queries import (
    get_api_service_list,
    get_distinct_api_service_names,
    insert_api_service,
    update_api_service,
    delete_api_service,
    get_function_library,
    insert_function_library_entry,
    update_function_library_entry,
    delete_function_library_entry,
    get_credential_requirements,
    upsert_credentials,
    delete_credentials,
    get_task_configuration,
    get_placeholder_task_id,
    insert_placeholder_task,
    get_task_config_by_id,
    delete_task_configuration,
    delete_fact_configuration,
    upsert_fact_configuration,
    get_distinct_task_names,
    get_task_execution_view,
    get_task_scheduling_view,
    get_active_db_sessions,
    kill_db_session,
    get_event_history,
    get_log_tables_simple,
    get_log_data_simple,
    update_task_configuration,
    get_task_summary_chart,
    get_db_size_chart,
    get_db_size_breakdown,
    get_task_logs,
    insert_task_configuration,
    get_task_performance_data,
    create_task_execution,
    update_task_execution,
    get_task_execution,
    get_recent_task_executions,
)
from .activities_queries import (
    get_activities_list,
    get_activity_by_id,
    get_activity_telemetry,
    get_segment_matches,
    get_recent_activities,
    get_activity_stats,
)
from .tri_tip_queries import (
    get_tri_tip_event,
    list_tri_tip_events,
    get_event_readings,
    get_active_event,
    initiate_tri_tip,
    place_tri_tip,
    add_tri_tip_reading,
    complete_tri_tip,
    abandon_tri_tip,
    # Exceptions
    TriTipError,
    TriTipActiveEventExistsError,
    TriTipStateError,
    TriTipNotFoundError,
)
from .volleyball_queries import (
    get_game,
    get_active_game,
    get_game_points,
    get_game_score,
    get_game_detail,
    list_game_history,
    create_game,
    add_point,
    remove_last_point,
    tag_last_point,
    end_game,
    abandon_game,
    VALID_EVENT_TYPES,
    # Exceptions
    VolleyballError,
    VolleyballActiveGameExistsError,
    VolleyballStateError,
    VolleyballNotFoundError,
)
from .exercise_queries import (
    get_exercise_timer,
    get_last_attempt,
    list_exercise_summaries,
    create_exercise,
    update_exercise,
    delete_exercise,
    create_attempt,
    # Exceptions
    ExerciseError,
    ExerciseNotFoundError,
    ExerciseNameConflictError,
    ExerciseValidationError,
)

__all__ = [
    # Health
    'get_weight_targets',
    'add_weight_target',
    'get_weight_viz_data',
    'add_photo_metadata',
    'add_body_dimensions',
    'get_heart_rate_timeseries',
    'get_sleep_data',
    # Music
    'get_rating_eligible_count',
    'get_isrc_dupe_count',
    'get_isrc_dupe_match',
    'get_playlist_config',
    'get_playlist_isrc_stats',
    'get_recent_plays',
    'get_rating_eligible_playlists',
    'get_playlists_not_containing_isrc',
    'process_isrc_dupe_acceptance',
    'add_isrc_to_local_playlist',
    'record_recommendation_decision',
    'remove_recommendation',
    'add_into_current_ratings',
    'update_playlist_config_weights',
    'record_rating_history',
    'update_ratings_from_view',
    'add_soft_rejection_exclusion',
    'get_matchup',
    'score_matchup',
    # Admin
    'get_api_service_list',
    'get_distinct_api_service_names',
    'insert_api_service',
    'update_api_service',
    'delete_api_service',
    'insert_function_library_entry',
    'update_function_library_entry',
    'delete_function_library_entry',
    'get_credential_requirements',
    'upsert_credentials',
    'delete_credentials',
    'get_task_configuration',
    'get_placeholder_task_id',
    'insert_placeholder_task',
    'get_task_config_by_id',
    'delete_task_configuration',
    'delete_fact_configuration',
    'upsert_fact_configuration',
    'get_distinct_task_names',
    'get_task_execution_view',
    'get_task_scheduling_view',
    'get_active_db_sessions',
    'kill_db_session',
    'get_event_history',
    'get_log_tables_simple',
    'get_log_data_simple',
    'update_task_configuration',
    'get_task_summary_chart',
    'get_db_size_chart',
    'get_db_size_breakdown',
    'get_task_logs',
    'insert_task_configuration',
    'get_task_performance_data',
    'create_task_execution',
    'update_task_execution',
    'get_task_execution',
    'get_recent_task_executions',
    # Activities
    'get_activities_list',
    'get_activity_by_id',
    'get_activity_telemetry',
    'get_segment_matches',
    'get_recent_activities',
    'get_activity_stats',
    # Tri-tip Timer
    'get_tri_tip_event',
    'list_tri_tip_events',
    'get_event_readings',
    'get_active_event',
    'initiate_tri_tip',
    'place_tri_tip',
    'add_tri_tip_reading',
    'complete_tri_tip',
    'abandon_tri_tip',
    'TriTipError',
    'TriTipActiveEventExistsError',
    'TriTipStateError',
    'TriTipNotFoundError',
    # Volleyball Scorekeeping
    'get_game',
    'get_active_game',
    'get_game_points',
    'get_game_score',
    'get_game_detail',
    'list_game_history',
    'create_game',
    'add_point',
    'remove_last_point',
    'tag_last_point',
    'end_game',
    'abandon_game',
    'VALID_EVENT_TYPES',
    'VolleyballError',
    'VolleyballActiveGameExistsError',
    'VolleyballStateError',
    'VolleyballNotFoundError',
    # Exercise Timer
    'get_exercise_timer',
    'get_last_attempt',
    'list_exercise_summaries',
    'create_exercise',
    'update_exercise',
    'delete_exercise',
    'create_attempt',
    'ExerciseError',
    'ExerciseNotFoundError',
    'ExerciseNameConflictError',
    'ExerciseValidationError',
]
